services:
  # Serviço de Banco de Dados (PostgreSQL)
  database:
    container_name: postgres_farmatech
    image: postgres:17
    ports:
      - '${DB_PORT}:5432'
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - farmatech-network

  # Interface Visual para o Banco (PGAdmin)
  pgadmin:
    container_name: pgadmin_farmatech
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${DB_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${DB_PASSWORD}
    ports:
      - '${PGADMIN_PORT}:80'
    depends_on:
      - database
    networks:
      - farmatech-network

  # Zookeeper (Necessário para o Kafka)
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper_farmatech
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - farmatech-network

  # Kafka (Mensageria para Notificações)
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka_farmatech
    hostname: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    networks:
      - farmatech-network

  # Servidor de E-mail Fake (Para testar notificações)
  smtp-server:
    image: haravich/fake-smtp-server
    container_name: fake-smtp-server
    ports:
      - "1080:1080" # Painel Web para ver os e-mails
      - "1025:1025" # Porta SMTP
    volumes:
      - smtp_data:/var/mail
    networks:
      - farmatech-network

  # Aplicação Spring Boot
  app:
    container_name: farmatech-api
    build: .
    ports:
      - "8090:8090"
    environment:
      # Sobrescreve as configs do application.properties para rodar DENTRO do Docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      # Configuração de E-mail apontando para o container fake
      - SPRING_MAIL_HOST=smtp-server
      - SPRING_MAIL_PORT=1025
      - SPRING_MAIL_USERNAME=""
      - SPRING_MAIL_PASSWORD=""
      # Configuração do Kafka interno
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092
    depends_on:
      - database
      - kafka
      - smtp-server
    networks:
      - farmatech-network

volumes:
  pgdata: {}
  smtp_data: {}

networks:
  farmatech-network:
    driver: bridge